[2024-01-16 16:17:52,765] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:17:51.298950+00:00 [queued]>
[2024-01-16 16:17:52,771] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:17:51.298950+00:00 [queued]>
[2024-01-16 16:17:52,772] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:17:52,772] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 16:17:52,772] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:17:52,781] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-16 16:17:51.298950+00:00
[2024-01-16 16:17:52,784] {standard_task_runner.py:52} INFO - Started process 1932 to run task
[2024-01-16 16:17:52,787] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-16T16:17:51.298950+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmp9e7p0oid', '--error-file', '/tmp/tmp2oexg8ho']
[2024-01-16 16:17:52,788] {standard_task_runner.py:80} INFO - Job 55: Subtask check_file_if_exists
[2024-01-16 16:17:52,826] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:17:51.298950+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 16:17:52,876] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T16:17:51.298950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T16:17:51.298950+00:00
[2024-01-16 16:17:56,003] {logging_mixin.py:115} INFO - Successfully install google-api-python-client
[2024-01-16 16:17:59,065] {logging_mixin.py:115} INFO - Successfully install google-auth-httplib2
[2024-01-16 16:18:02,013] {logging_mixin.py:115} INFO - Successfully install google-auth
[2024-01-16 16:18:05,055] {logging_mixin.py:115} INFO - Successfully install google-auth-oauthlib
[2024-01-16 16:18:05,070] {logging_mixin.py:115} INFO - Credentials from token ya29.a0AfB_byCbo1LuaVau_lph7bh7WjmnYEa740lh58RaXUYRjPfEc1xAYOFdmhd5-NtKhAcgpYTZSoZkkFC2aMHWHib8LJIFRlD5WJBZYON-TITr2Jb3lZI01KfKnV6F7e_-MGDSNZB-V9cpFMW_YKpo6ZhvimsHofRl5Fl7OgaCgYKAaQSARMSFQHGX2MiNQbSQHbzKQLVfmHflPJQAw0173
[2024-01-16 16:18:05,071] {logging_mixin.py:115} INFO - <google.oauth2.credentials.Credentials object at 0xffff9451aa50>
[2024-01-16 16:18:06,559] {logging_mixin.py:115} INFO - [{'id': '1rzPInbJFi86HYocPCcptsDflfIYvkzqF', 'name': 'dataset'}]
[2024-01-16 16:18:06,562] {logging_mixin.py:115} INFO - The 'dataset' folder exists in 'Shared with me'.
[2024-01-16 16:18:06,999] {logging_mixin.py:115} INFO - dataset_files: [{'id': '1bORWzTe1VDOzGpiFpD0KJ78MN_rYr7gp', 'name': '2023-10-02.csv'}]
[2024-01-16 16:18:08,003] {logging_mixin.py:115} INFO - Downloaded file 2023-10-02.csv from Google Drive.
[2024-01-16 16:18:08,015] {python.py:173} INFO - Done. Returned value was: process_csv
[2024-01-16 16:18:08,036] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240116T161751, start_date=20240116T161752, end_date=20240116T161808
[2024-01-16 16:18:08,085] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-16 16:18:08,127] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
