[2024-01-16 16:20:12,517] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:20:10.864901+00:00 [queued]>
[2024-01-16 16:20:12,524] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:20:10.864901+00:00 [queued]>
[2024-01-16 16:20:12,524] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:20:12,524] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2024-01-16 16:20:12,525] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-16 16:20:12,534] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): check_file_if_exists> on 2024-01-16 16:20:10.864901+00:00
[2024-01-16 16:20:12,537] {standard_task_runner.py:52} INFO - Started process 2018 to run task
[2024-01-16 16:20:12,540] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_transfer_gdrive_to_postgresql', 'check_file_if_exists', 'manual__2024-01-16T16:20:10.864901+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dag_gdrive_to_postgres.py', '--cfg-path', '/tmp/tmp1pf5n0yi', '--error-file', '/tmp/tmp7gkuz_cz']
[2024-01-16 16:20:12,541] {standard_task_runner.py:80} INFO - Job 58: Subtask check_file_if_exists
[2024-01-16 16:20:12,580] {task_command.py:369} INFO - Running <TaskInstance: dag_transfer_gdrive_to_postgresql.check_file_if_exists manual__2024-01-16T16:20:10.864901+00:00 [running]> on host 3c1ede9470c0
[2024-01-16 16:20:12,630] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfer_gdrive_to_postgresql
AIRFLOW_CTX_TASK_ID=check_file_if_exists
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T16:20:10.864901+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-16T16:20:10.864901+00:00
[2024-01-16 16:20:15,783] {logging_mixin.py:115} INFO - Successfully install google-api-python-client
[2024-01-16 16:20:18,879] {logging_mixin.py:115} INFO - Successfully install google-auth-httplib2
[2024-01-16 16:20:21,742] {logging_mixin.py:115} INFO - Successfully install google-auth
[2024-01-16 16:20:24,611] {logging_mixin.py:115} INFO - Successfully install google-auth-oauthlib
[2024-01-16 16:20:24,622] {logging_mixin.py:115} INFO - Credentials from token ya29.a0AfB_byCbo1LuaVau_lph7bh7WjmnYEa740lh58RaXUYRjPfEc1xAYOFdmhd5-NtKhAcgpYTZSoZkkFC2aMHWHib8LJIFRlD5WJBZYON-TITr2Jb3lZI01KfKnV6F7e_-MGDSNZB-V9cpFMW_YKpo6ZhvimsHofRl5Fl7OgaCgYKAaQSARMSFQHGX2MiNQbSQHbzKQLVfmHflPJQAw0173
[2024-01-16 16:20:24,622] {logging_mixin.py:115} INFO - <google.oauth2.credentials.Credentials object at 0xffff9451b210>
[2024-01-16 16:20:25,719] {logging_mixin.py:115} INFO - [{'id': '1rzPInbJFi86HYocPCcptsDflfIYvkzqF', 'name': 'dataset'}]
[2024-01-16 16:20:25,720] {logging_mixin.py:115} INFO - The 'dataset' folder exists in 'Shared with me'.
[2024-01-16 16:20:26,115] {logging_mixin.py:115} INFO - dataset_files: [{'id': '1bORWzTe1VDOzGpiFpD0KJ78MN_rYr7gp', 'name': '2023-10-02.csv'}]
[2024-01-16 16:20:27,219] {logging_mixin.py:115} INFO - Downloaded file 2023-10-02.csv from Google Drive.
[2024-01-16 16:20:27,248] {python.py:173} INFO - Done. Returned value was: process_csv
[2024-01-16 16:20:27,269] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_transfer_gdrive_to_postgresql, task_id=check_file_if_exists, execution_date=20240116T162010, start_date=20240116T162012, end_date=20240116T162027
[2024-01-16 16:20:27,294] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-16 16:20:27,318] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
